//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUPeliculas
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
        }

        [ScaffoldColumn(false)]
        public int idPelicula { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre de la película es requerido"), MaxLength(55)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Fecha de lanzamiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechalanzamiento { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El tiempo de duración de la película es requerido."), MaxLength(55)]
        [Display(Name = "Duracion")]
        public string duracion { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La categoría es requerida"), MaxLength(55)]
        [Display(Name = "Categoria")]
        public string categoría { get; set; }
    }
}
